telegram:
  api_id: 14631157
  api_hash: "aa7c2b3be68a7488abdb9de6ce78d311"
  token: "5927429053:AAGNa4VeQEOM5_Fj_mmq-21OqB6qr308DDU"
  lang_code: !!str "en"
  max_upload_tasks: 5
  url_validation_regexes:
    - "^http(s)?:\\/\\/.+$"
  allowed_users:  # Multiple users/groups are allowed.
    - id: 5380833276  # User or group ID.
      send_startup_message: True
      download_media_type: "VIDEO"
      save_to_storage:  False
      use_url_regex_match: True
      upload:
        upload_video_file: !!bool true
        upload_video_max_file_size: 2147483648
        forward_to_group: False
        forward_group_id: -00000000000  # Group or channel ID.
        silent: False
        video_caption:
          include_title: True
          include_filename:  False
          include_link:  True
          include_size:  True
  api:
    upload_video_file: False
    upload_video_max_file_size: 2147483648
    upload_to_chat_ids:  # User, group or channel IDs.
      - 22222222222
      - -33333333333
    silent: False
    video_caption:
      include_title: True
      include_filename: False
      include_link:  True
      include_size: True
ytdlp:
  version_check_enabled: True
  version_check_interval: 86400
  notify_users_on_new_version: True
